# Generated by Django 4.0.2 on 2022-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default=None, upload_to='img_avata/%Y/%m'),
        ),
    ]
