# Generated by Django 4.0.2 on 2022-04-18 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bill_user_bill_booking_user_book_payment_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='routes',
        ),
        migrations.AddField(
            model_name='train',
            name='route_train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_trains', to='booking.routes'),
        ),
    ]
