# Generated by Django 4.0.2 on 2022-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_train_routes_train_route_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='ending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
